// Code generated by hertz generator.

package person

import (
	"context"
	"fmt"

	person "hertz_demo/biz/model/hertz/person"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/pkg/errors"
)

// PersonInfo .
// @router /person_info [GET]
func PersonInfo(ctx context.Context, c *app.RequestContext) {
	var err error
	var req person.PersonReq
	err = c.BindAndValidate(&req)
	if err != nil {
		fmt.Printf("%v", err.Error())
		_ = c.Error(errors.WithStack(err))
		return
	}

	resp := &person.PersonResp{
		Name: req.Name,
		Age:  req.Age,
		City: req.City,
	}

	c.JSON(200, resp)
}
