// Code generated by hertz generator.

package Person

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _personinfoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _person_infoMw() []app.HandlerFunc {
	// your code...
	return nil
}
